name: CUDA Compilation Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: "11.7.0"

      - name: Compile CUDA code
        run: |
          nvcc vadd.cu -o vadd

      - name: Run CUDA binary
        run: |
          ./vadd
