name: CUDA Compilation Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CUDA
        uses: jakejarvis/setup-cuda@v1
        with:
          cuda-version: 11.0

      - name: Compile CUDA code
        run: |
          nvcc vadd.cu -o vadd

      - name: Run CUDA binary
        run: |
          ./vadd
