name: CUDA Compilation Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CUDA
        uses: nvidia/cuda-toolkit@v1
        with:
          version: "11.0"

      - name: Compile CUDA code
        run: |
          nvcc vadd.cu -o vadd

      - name: Run CUDA binary
        run: |
          ./vadd
