name: Cuda compilation test
on: [push]

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.8 
        id: cuda-toolkit 
        with:
          cuda: '11.7.0'

      - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

      - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - run: nvcc -V
